### ISSUE TITLE
WP constants not found

### ISSUE THREAD

**Issue by joehoyle** [humanmade/psalm-plugin-wordpress#1]
Such as HOUR_IN_SECONDS

**Comment by szepeviktor** [comment]
There are two types on core constants

- _use_ ones -> https://github.com/szepeviktor/phpstan-wordpress/blob/master/bootstrap.php
- and _do not use_ :) ones

(secret information: _do not use_ ones live here https://github.com/php-stubs/wordpress-globals)

**Comment by ssnepenthe** [comment]
A few more for you:

WP_CONTENT_DIR
COOKIE_DOMAIN
COOKIEPATH
LOGGED_IN_COOKIE
SECURE_AUTH_COOKIE
AUTH_COOKIE
