### ISSUE TITLE
Use existing wordpress-stubs

### ISSUE THREAD

**Issue by swissspidy** [humanmade/psalm-plugin-wordpress#5]
Any reason not to use https://github.com/php-stubs/wordpress-stubs?

**Comment by joehoyle** [comment]
Ah Nice, that certainly could be an option to reduce complexity. At the moment stubs are generated with Psalm, which is a bit of a faff to keep updated.

@johnbillion also suggested the same in using his project for the action / filter reference which I'm interested in too. Mostly I just rigged up what I could to get this working, but I'd rather offload work where possible!

**Comment by dwenaus** [comment]
I first installed the php-stubs/wordpress-stubs plugin which ends up taking 16.1 seconds on my system to check one file. I think tried the wordpress.php stubs file in this repo and it only took 9.5 seconds. The file size is quite substantial as well 3.7 MB for php-stubs vs 1.43 MB for this repo.

**Comment by joehoyle** [comment]
This is not included in https://github.com/humanmade/psalm-plugin-wordpress/releases/tag/2.0.0

**Comment by joehoyle** [comment]
@dwenaus hmm that's interesting, I was intentionally removing some parts when generating the stubs (like some internal libraries), it could be that php-stubs is not doing that.
