### ISSUE TITLE
Attempts to Use Non-Existing Files

### ISSUE THREAD

**Issue by XedinUnknown** [humanmade/psalm-plugin-wordpress#8]
## The Symptom
Psalm continues to be ignorant of WP symbols even when the plugin is present and used.

## Reproducing
1. Use `WP_Site` anywhere in your code.
2. Install this plugin and activate it with Psalm.
3. Run Psalm.
4. Observe symptom: Psalm will report `UndefinedClass` `WP_Site`.

## Possible Cause
As described [here][1], the plugin points Psalm to stub files that don't exist. The reasons are the following:

1. `php-stubs/wordpress-stubs` is never installed, because it is a dev-dependency of this plugin, and this plugin wil be used in another project, whereas `require-dev` is root only.
2. This plugin points to files in a `vendor` dir relative to its root dir, which of course would not exist because when used as a plugin the root will be elsewhere.

[1]: https://github.com/vimeo/psalm/issues/4383#issuecomment-779844220

**Comment by joehoyle** [comment]
Whoops, I think this is because I run it symlinked locally, will fix up!

**Comment by joehoyle** [comment]
Released in https://github.com/humanmade/psalm-plugin-wordpress/releases/tag/2.0.3

**Comment by XedinUnknown** [comment]
Thanks for the quick response, and even release!

I see that you have now included `php-stubs/wordpress-stubs` as a non-dev dependency. This solves one of the problems on my list, although it introduces another: stubs will now be part of production.

Regardless, this still does not solve the other problem, which is that the stubs file path is relative to this plugin's folder, not to the root. Still doesn't work, therefore.

**Comment by joehoyle** [comment]
> This solves one of the problems on my list, although it introduces another: stubs will now be part of production.

You should have psalm things as dev deps, so they shouldn't be part of your composer product build, no?

> Regardless, this still does not solve the other problem, which is that the stubs file path is relative to this plugin's folder, not to the root. Still doesn't work, therefore.

Doh, that's again due to my symlinking!

**Comment by XedinUnknown** [comment]
> You should have psalm things as dev deps, so they shouldn't be part of your composer production build, no?

True, my bad. Indeed, if Psalm is `require-dev`, then its strict requirements will only be installed when root installs for dev.

> Doh, that's again due to my symlinking!

Cheers!

**Comment by joehoyle** [comment]
Sorry for the delay here folks. I switched to using `getcwd()` in https://github.com/humanmade/psalm-plugin-wordpress/blob/master/Plugin.php, which should fix this up.

**Comment by joehoyle** [comment]
Closing as fixed.
